#pragma once
#define CONFIG_H
#define ARDUINOJSON_ENABLE_ARDUINO_STRING 1
#define ARDUINOJSON_ENABLE_ARDUINO_STREAM 0
#define ARDUINOJSON_ENABLE_ARDUINO_PRINT 0
#define ARDUINOJSON_ENABLE_PROGMEM 0
#define MATRIX_WIDTH 16
#define MATRIX_HEIGHT 16
#define ASSET_ERROR_COLOR 255,0,0
